
title: Rizwan Shaikh | Digital Marketing Professional
email: rzwnsh00@gmail.com
baseurl: ""
url: "https://onrevm.online/"
permalink: pretty
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
